name: Odoo CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Check Module
        run: |
          pylint credit_limit_control || true
